#!/usr/bin/env bash

# Decompiles hybris jar files using CFR decompiler
#
# source: https://github.com/sergaks/y-scripts

CFR_JAR=cfr_0_122.jar
CFR_URL="http://www.benf.org/other/cfr/$CFR_JAR"
TMP_DIR="/tmp"
HYBRIS_DIR=`y-whereis`

if [ $? -ne 0 ]; then
	echo "FAILURE"
	exit 1
fi

DECOMPILED_SRC_DIR="$HYBRIS_DIR/../../data/decompiled_src"

echo "Getting cfr decompliler"
wget -nc -O "$TMP_DIR/$CFR_JAR" $CFR_URL 

echo "Cleaning directory with decompiled source"
rm -rf "$DECOMPILED_SRC_DIR"

echo "Starting jar decompiling"
find "$HYBRIS_DIR/../.." \( \
		-regex ".*bin/[^/]*.jar" \
		-not -path "*tomcat*" \
		-not -path "*atddrunner*" \
	-or \
		-name "*_bof.jar" \) \
	-exec java -jar $TMP_DIR/$CFR_JAR "{}" --outputdir "$DECOMPILED_SRC_DIR"/ \;

echo "Finished, decompiled sources available in folder: $DECOMPILED_SRC_DIR"