#!/usr/bin/env bash

# Alias for hybrisserver.sh in hybris platform
#
# source: https://github.com/sergaks/y-scripts

HYBRIS_DIR=`y-whereis`

if [ $? -ne 0 ]; then
	echo "FAILURE"
	exit 1
fi

cd "$HYBRIS_DIR" && exec ./hybrisserver.sh "$@"