#!/usr/bin/env bash

CONSOLE_OUTPUT_FILE="/tmp/hybris-update.log"

# if [ -z "$1"]
#   then
#   	echo "Path to hybris directory required"
#     echo "Usage: hybris-update.sh <path-to-hybris-directory>"
#     exit 1
# fi

ant updatesystem | tee "$CONSOLE_OUTPUT_FILE"

FAILURES=`cat "$CONSOLE_OUTPUT_FILE" | sed -n "/Updating system/,/FINISHED/p" | grep -e "WARN\|ERROR"`


if [ -n "$FAILURES" ]; then
	echo "$FAILURES"
	echo "======================================"
    echo "FAILED (see errors above)"
    exit 1
else 
	echo "======================================"
	echo "SUCCESS (no errors)"
fi 