#!/usr/bin/env bash

# Search for hybris platform folder based on current working directory
#
# source: https://github.com/sergaks/y-scripts

HYBRIS_PLATFORM_DIR="bin/platform"

function purge_hybris_pathes()
{
    for f in "${pathes[@]}"; do
		if [ -d "$f/$HYBRIS_PLATFORM_DIR" ]; then
			hybris_pathes+=("$f/$HYBRIS_PLATFORM_DIR")
		fi
	done
}

function lookup_in_current_dir() 
{
	CURRENT_DIR=`pwd`
	if [[ $CURRENT_DIR == *"hybris"* ]]; then
	  pathes+=(`echo $CURRENT_DIR | sed -n 's/hybris.*$/hybris/p'`)
	fi
}

function lookup_in_subdirectories() 
{
	while IFS=  read -r -d $'\0'; do
    pathes+=("$REPLY")
	done < <(find .  -maxdepth 3 -type d -name "hybris" -print0)
}

function lookup_nearby() 
{
	PARENT=".."
	for (( i = 0; i < 5; i++ )); do
		while IFS=  read -r -d $'\0'; do
		pathes+=("$REPLY")
		done < <(find $PARENT -maxdepth 3 -type d -name "hybris" -print0)
		PARENT+="/.."
		purge_hybris_pathes
		if [ ${#hybris_pathes[@]} -ne 0 ]; then
			break
		fi
	done
}

# search for hybris platform path candidates
pathes=()
lookup_in_current_dir
lookup_in_subdirectories

# filter only pathes with hybris platform directory available
hybris_pathes=()
purge_hybris_pathes

# if nothing found search in adjacent folders as last resort 
if [ ${#hybris_pathes[@]} -eq 0 ]; then
	lookup_nearby
fi

if [ ${#hybris_pathes[@]} -eq 0 ]; then
    >&2 echo "hybris isn't detected anywhere nearby current folder, please go to hybris folder"
    exit 1
elif [ ${#hybris_pathes[@]} -eq 1 ]; then
	echo "${hybris_pathes[0]}"
	exit 0
else
	>&2 echo "multiple hybris projects found, please go to correct one and execute the command again"
	>&2 printf '%s\n' "${hybris_pathes[@]}"
	exit 1
fi
